# name of the software
name: EDGE DESIGN

# list of additional links on the right of the top menu
headerLinks:

# list if additional links on the footer
footerLinks:
  - title: © 2015 EDGE DESIGN
    url: https://www.lucentsky.com/
  - title: © 2014 EDGE DESIGN
    url: https://www.lucentsky.com/
  
# header
header:
  color1: "#ffffff"
  color2: "#ffffff"
  trianglify: false

# google analytics
analytics:
  account: UA-38808585-2
  domain: support.lucentsky.com

exclude: ['bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
